name: 'DustiLock'
description: 'DustiLock is a tool to find which of your dependencies is susceptible to Dependency Confusion attack'
inputs:
  recursive:
    description: 'scan recursively (default = false)'
    required: false
    default: ''
  path:
    description: 'custom scan dir (e.g. "subdir1/subdir2")'
    required: false
    default: ''
  audit:
    description: 'disable failing the build when having alerts (default = false)'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: "shield"
  color: "green"
