name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get semantic release info
      id: semantic_release_info
      uses: jossef/action-semantic-release-info@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Build the Docker image
      if: ${{ steps.semantic_release_info.outputs.git_tag }}
      run: docker build -t checkmarx/dustilock:${{ steps.semantic_release_info.outputs.git_tag }} .

    - name: Tag version
      if: ${{ steps.semantic_release_info.outputs.git_tag }}
      id: tag_version
      run: |
        git config --local user.email "devops@dusti.co"
        git config --local user.name "Dustico DevOps"
        git tag ${{ steps.semantic_release_info.outputs.git_tag }}
        git push
        echo ::set-output name=latest_commit_hash::$(git rev-parse HEAD)

    - name: Create GitHub release
      if: ${{ steps.semantic_release_info.outputs.git_tag }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ steps.semantic_release_info.outputs.git_tag }}
        release_name: ${{ steps.semantic_release_info.outputs.git_tag }}
        body: ${{ steps.semantic_release_info.outputs.notes }}
        commitish: ${{ steps.tag_version.outputs.latest_commit_hash }}
        draft: false
        prerelease: false
